[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ibeat-kidney-ssa"
version = "0.0.0"
dependencies = [
  'tqdm',
  'numpy',
  'scipy',
  'dbdicom',
  'vreg',
  'pyvista', 
  'scikit-learn',
  'dask',
  'numpyradiomics',
  'pydmr',
]

[tool.setuptools.packages.find]
where = ["src"]